//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumno.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabla
    {
        public int Id { get; set; }
        public string NombreAlumno { get; set; }
        public string ApellidoAlumno { get; set; }
        public int CalificacionAlumno { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
